# Site settings
title: billhunt.dev Slides
email: hello@billhunt.email

description: > # this means to ignore newlines until "baseurl:"
  Slide decks for Bill Hunt

baseurl: "/slides"
url: "https://krusynth.github.io/slides/"

# Build settings
markdown: redcarpet

collections:
  slides:
    output: true
    permalink: "/:path/"
